Repository google-apis-rs/google-cloud-rs, pull requests merged in 2020-07, with the labels that each got.

#18 Fix storage tests, a few bucket fields are optional
  google-cloud/src/storage/api/bucket.rs
Labels: C-bug, C-tests, M-storage, P-medium

#17 Revisited how authentication tokens are kept up-to-date
  .github/workflows/ci.yaml
  .gitignore
  google-cloud/Cargo.toml
  google-cloud/src/authorize/mod.rs
  google-cloud/src/datastore/client.rs
  google-cloud/src/error.rs
  google-cloud/src/pubsub/client.rs
  google-cloud/src/pubsub/message.rs
  google-cloud/src/pubsub/subscription.rs
  google-cloud/src/pubsub/topic.rs
  google-cloud/src/storage/bucket.rs
  google-cloud/src/storage/client.rs
  google-cloud/src/storage/object.rs
  google-cloud/src/tests/datastore.rs
  google-cloud/src/tests/pubsub.rs
  google-cloud/src/tests/storage.rs
  google-cloud/src/tests/vision.rs
  google-cloud/src/vision/client.rs
Labels: C-dependencies, C-refactor, P-medium

#20 Make reqwest as optional
  google-cloud/Cargo.toml
  google-cloud/src/authorize/mod.rs
  google-cloud/src/datastore/client.rs
  google-cloud/src/error.rs
  google-cloud/src/pubsub/client.rs
  google-cloud/src/vision/client.rs
Labels: C-dependencies, P-medium

#21 Replace frank-jwt with jsonwebtoken
  google-cloud/Cargo.toml
  google-cloud/src/authorize/mod.rs
  google-cloud/src/error.rs
  google-cloud/src/lib.rs
  google-cloud/src/utils.rs
Labels: C-dependencies, P-medium
