Repository google-apis-rs/google-cloud-rs, pull requests merged in 2020-08, with the labels that each got.

#22 pubsub: Swap id and name for struct topic and subscription
  google-cloud/src/pubsub/client.rs
  google-cloud/src/pubsub/message.rs
  google-cloud/src/pubsub/subscription.rs
  google-cloud/src/pubsub/topic.rs
Labels: C-enhancement, C-refactor, M-pubsub, P-medium

#23 Do not use env! to inline secrets
  google-cloud/src/tests/datastore.rs
  google-cloud/src/tests/mod.rs
  google-cloud/src/tests/pubsub.rs
  google-cloud/src/tests/storage.rs
  google-cloud/src/tests/vision.rs
Labels: C-refactor, P-medium

#28 Prepare for a `0.1.0` crates.io release
  README.md
  google-cloud-derive/Cargo.toml
  google-cloud-derive/README.md
  google-cloud/Cargo.toml
  google-cloud/README.md
  google-cloud/src/datastore/entity.rs
  google-cloud/src/error.rs
Labels: C-documentation, P-medium

#29 Filled missing attributes in `Cargo.toml`
  google-cloud-derive/Cargo.toml
Labels: C-bug, P-low

#30 Removed keyword to get to a count of 5
  google-cloud-derive/Cargo.toml
Labels: C-bug, P-low
