Repository google-apis-rs/google-cloud-rs, pull requests merged in 2021-03, with the labels that each got.

#35 Update to tokio 1.0 and friends
  google-cloud/Cargo.toml
  google-cloud/src/authorize/mod.rs
  google-cloud/src/datastore/api/google.api.rs
  google-cloud/src/datastore/api/google.datastore.v1.rs
  google-cloud/src/pubsub/api/google.api.rs
  google-cloud/src/pubsub/api/google.pubsub.v1.rs
  google-cloud/src/vision/api/google.api.rs
  google-cloud/src/vision/api/google.cloud.vision.v1.rs
  google-cloud/src/vision/api/google.longrunning.rs
  google-cloud/src/vision/api/google.r#type.rs
  google-cloud/src/vision/api/google.rpc.rs
Labels: C-dependencies, P-medium

#41 General dependency upgrades
  google-cloud/Cargo.toml
Labels: C-dependencies, P-medium

#42 fix(storage): Fixed error when bucket listing turns out to be empty
  google-cloud/src/storage/api/bucket.rs
Labels: C-bug, M-storage, P-high

#33 feature(pubsub): Added ReceiveOptions for message pulling
  google-cloud/src/pubsub/subscription.rs
  google-cloud/src/tests/pubsub.rs
Labels: C-enhancement, M-pubsub, P-medium

#43 Regenerated protobuf-related files
  google-cloud/src/vision/api/google.cloud.vision.v1.rs
Labels: P-low

#44 fix(pubsub): Changed default `max_messages`
  google-cloud/src/pubsub/subscription.rs
Labels: C-refactor, M-pubsub, P-medium

#45 release(v0.2.0): Prepare v0.2.0 release
  CHANGELOG.md
  README.md
  google-cloud-derive/Cargo.toml
  google-cloud-derive/README.md
  google-cloud/Cargo.toml
  google-cloud/README.md
Labels: C-release, P-high

#46 fix(storage): Fixed user values not being percent-encoded
  google-cloud/Cargo.toml
  google-cloud/src/storage/bucket.rs
  google-cloud/src/storage/client.rs
  google-cloud/src/storage/object.rs
Labels: C-bug, M-storage, P-medium

#47 release(v0.2.1): Prepare v0.2.1 release
  .gitignore
  CHANGELOG.md
  google-cloud-derive/Cargo.toml
  google-cloud/Cargo.toml
Labels: C-release, P-medium
